export interface Team {
    id: number;
    name: string;
    abbrev: string;
    logoUrl: string;
    conference: string;
    division: string;
    gamesPlayed: number;
    wins: number;
    losses: number;
    otLosses: number;
    points: number;
    pointPercentage: number;
    row: number;
    rowPercentage: number;
    goalsFor: number;
    goalsAgainst: number;
    homeWins: number;
    homeLosses: number;
    homeOtLosses: number;
    homeGoalsFor: number;
    homeGoalsAgainst: number;
    roadWins: number;
    roadLosses: number;
    roadOtLosses: number;
    roadGoalsFor: number;
    roadGoalsAgainst: number;
    currentWinStreak: number;
}